import { z } from 'zod'

export const BookingRequestSchema = z.object({
  id: z.string().uuid(),
  property_id: z.string().uuid(),
  unit_id: z.string().uuid(),
  tenant_id: z.string().uuid().optional(),
  num_occupants: z.number(),
  start_date: z.date(),
  status: z.string(),
  agreed_price: z.number().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
})

export const BookingSchema = z.object({
  id: z.string().uuid(),
  property_id: z.string().uuid(),
  unit_id: z.string().uuid(),
  user_id: z.string().uuid().optional(),
  booking_type: z.enum(['daily', 'weekly', 'monthly', 'yearly', 'custom']),
  status: z.string(),
  start_date: z.date(),
  end_date: z.date(),
  base_price_at_booking: z.number().optional(),
  security_deposit: z.number().optional(),
  discount_amount: z.number().optional(),
  tax_amount: z.number().optional(),
  total_amount: z.number().optional(),
  currency: z.enum(['IDR', 'USD']),
  source: z.enum([
    'direct',
    'agent',
    'referral',
    'organic',
    'paid_ads',
    'social_media',
  ]),
  referral_code: z.string().optional(),
  utm_source: z.string().optional(),
  utm_medium: z.string().optional(),
  utm_campaign: z.string().optional(),
  confirmed_at: z.date().optional(),
  cancelled_at: z.date().optional(),
  completed_at: z.date().optional(),
  rejected_at: z.date().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
})

export const CreateBookingRequestInput = z.object({
  property_id: z.string().uuid(),
  unit_id: z.string().uuid(),
  tenant_id: z.string().uuid().optional(),
  num_occupants: z.number(),
  start_date: z.date(),
  agreed_price: z.number().optional(),
})

export const CreateBookingInput = z.object({
  property_id: z.string().uuid(),
  unit_id: z.string().uuid(),
  user_id: z.string().uuid().optional(),
  booking_type: z.enum(['daily', 'weekly', 'monthly', 'yearly', 'custom']),
  start_date: z.date(),
  end_date: z.date(),
  base_price_at_booking: z.number().optional(),
  security_deposit: z.number().optional(),
  discount_amount: z.number().optional(),
  tax_amount: z.number().optional(),
  total_amount: z.number().optional(),
  currency: z.enum(['IDR', 'USD']),
  source: z.enum([
    'direct',
    'agent',
    'referral',
    'organic',
    'paid_ads',
    'social_media',
  ]),
  referral_code: z.string().optional(),
  utm_source: z.string().optional(),
  utm_medium: z.string().optional(),
  utm_campaign: z.string().optional(),
  booking_request_id: z.string().uuid().optional(),
})
