import {
  ajukanBooking,
  approveKyc,
  createTransaksiBooking,
  createPayment,
  createRefund,
  getBookingSaya,
  getDaftarRequestBooking,
  getStatistikPemilik,
  getBookingAktif,
  konfirmasiPembayaranDP,
  konfirmasiPelunasan,
  listKycRequests,
  listPayments,
  setujuiBooking,
  submitKyc,
  tolakBooking,
  updateRefundStatus,
  verifyPayment,
  batalkanBooking,
  refund,
  getRefundStatus,
  prosesRefundDP,
} from './transactions'
import { searchLocations, reverseGeocode } from './geocoding'
import { addTodo, listTodos } from './todos'
import {
  checkPropertyAvailability,
  checkUnitAvailability,
  createProperty,
  createUnit,
  deleteProperty,
  deleteUnit,
  getProperty,
  getPropertyWithRelations,
  listProperties,
  listFeaturedProperties,
  updateProperty,
  updateUnit,
} from './properties'
import {
  confirmBookingRequest,
  createBooking as createLegacyBooking,
  createBookingRequest,
  getPropertyBookingRequests,
  getPropertyBookings,
} from './bookings'
import {
  ajukanPemesanan,
  batalPemesanan,
  listPemesananProperti,
  listPemesananSaya,
  setujuiPemesanan,
  tolakPemesanan,
} from './pemesanan'
import { getUserLocale, setUserLocale } from './preferences'

export default {
  listTodos,
  addTodo,
  listProperties,
  listFeaturedProperties,
  getProperty,
  getPropertyWithRelations,
  createProperty,
  updateProperty,
  deleteProperty,
  createUnit,
  updateUnit,
  deleteUnit,
  checkUnitAvailability,
  checkPropertyAvailability,
  createBookingRequest,
  getPropertyBookingRequests,
  getPropertyBookings,
  createBooking: createLegacyBooking,
  confirmBookingRequest,
  ajukanPemesanan,
  setujuiPemesanan,
  tolakPemesanan,
  batalPemesanan,
  listPemesananSaya,
  listPemesananProperti,
  createTransaksiBooking,
  ajukanBooking,
  konfirmasiPembayaranDP,
  setujuiBooking,
  tolakBooking,
  getStatistikPemilik,
  getBookingAktif,
  konfirmasiPelunasan,
  getBookingSaya,
  getDaftarRequestBooking,
  createPayment,
  verifyPayment,
  submitKyc,
  listKycRequests,
  approveKyc,
  createRefund,
  updateRefundStatus,
  listPayments,
  batalkanBooking,
  refund,
  prosesRefundDP,
  getRefundStatus,
  getUserLocale,
  setUserLocale,
  searchLocations,
  reverseGeocode,
}
