import {
  getStatistikPlatform,
  getKonfigurasiPlatform,
  updateKonfigurasiPlatform,
  getAllBookings,
  getAllUsers,
  updateUserRole,
  updateUserStatus,
  getKycVerifications,
  getInspections,
  getMaintenanceReports,
  getAuditLogs,
} from './admin'
import {
  ajukanBooking,
  approveKyc,
  createTransaksiBooking,
  createPaymentLink,
  createRefund,
  getBookingSaya,
  getDaftarRequestBooking,
  getStatistikPemilik,
  getBookingAktif,
  konfirmasiPembayaranDP,
  konfirmasiPelunasan,
  listKycRequests,
  listPayments,
  setujuiBooking,
  submitKyc,
  tolakBooking,
  updateRefundStatus,
  verifyPayment,
  batalkanBooking,
  refund,
  getRefundStatus,
  prosesRefundDP,
  getPaymentDeadline,
  getBookingDetail,
  checkRoomAvailability,
  extendBooking,
  getBookingExtensionHistory,
} from './transactions'
import {
  createPayment,
  getPaymentStatus,
  processPaymentWebhook,
  createMidtransPayment,
  getTransactionStatus,
} from './transaction'
import { searchLocations, reverseGeocode } from './geocoding'
import { addTodo, listTodos } from './todos'
import {
  checkPropertyAvailability,
  checkUnitAvailability,
  createProperty,
  createUnit,
  deleteProperty,
  deleteUnit,
  getProperty,
  getPropertyWithRelations,
  listProperties,
  listFeaturedProperties,
  searchRooms,
  updateProperty,
  updateUnit,
} from './properties'
import {
  confirmBookingRequest,
  createBooking as createLegacyBooking,
  createBookingRequest,
  getPropertyBookingRequests,
  getPropertyBookings,
} from './bookings'
import {
  ajukanPemesanan,
  batalPemesanan,
  listPemesananProperti,
  listPemesananSaya,
  setujuiPemesanan,
  tolakPemesanan,
} from './pemesanan'
import { getUserLocale, setUserLocale } from './preferences'
import {
  addToWishlist,
  removeFromWishlist,
  getMyWishlist,
  checkWishlistStatus,
  getWishlistCount,
} from './wishlist'
import {
  getNotifications,
  getUnreadNotifications,
  markNotificationRead,
  markAllNotificationsRead,
} from './notifications'
import { getUpcomingExpirations, getMonthlyRevenue } from './owner'

export default {
  listTodos,
  addTodo,
  listProperties,
  listFeaturedProperties,
  searchRooms,
  getProperty,
  getPropertyWithRelations,
  createProperty,
  updateProperty,
  deleteProperty,
  createUnit,
  updateUnit,
  deleteUnit,
  checkUnitAvailability,
  checkPropertyAvailability,
  createBookingRequest,
  getPropertyBookingRequests,
  getPropertyBookings,
  createBooking: createLegacyBooking,
  confirmBookingRequest,
  ajukanPemesanan,
  setujuiPemesanan,
  tolakPemesanan,
  batalPemesanan,
  listPemesananSaya,
  listPemesananProperti,
  createTransaksiBooking,
  ajukanBooking,
  konfirmasiPembayaranDP,
  setujuiBooking,
  tolakBooking,
  getStatistikPemilik,
  getBookingAktif,
  konfirmasiPelunasan,
  getBookingSaya,
  getDaftarRequestBooking,
  createPayment,
  createMidtransPayment,
  getTransactionStatus,
  createPaymentLink,
  getPaymentStatus,
  processPaymentWebhook,
  verifyPayment,
  submitKyc,
  listKycRequests,
  approveKyc,
  createRefund,
  updateRefundStatus,
  listPayments,
  batalkanBooking,
  refund,
  prosesRefundDP,
  getRefundStatus,
  getPaymentDeadline,
  getBookingDetail,
  checkRoomAvailability,
  extendBooking,
  getBookingExtensionHistory,
  getUserLocale,
  setUserLocale,
  searchLocations,
  reverseGeocode,
  getStatistikPlatform,
  getKonfigurasiPlatform,
  updateKonfigurasiPlatform,
  getAllBookings,
  getAllUsers,
  updateUserRole,
  updateUserStatus,
  getKycVerifications,
  getInspections,
  getMaintenanceReports,
  getAuditLogs,
  addToWishlist,
  removeFromWishlist,
  getMyWishlist,
  checkWishlistStatus,
  getWishlistCount,
  getUnreadNotifications,
  getNotifications,
  markNotificationRead,
  markAllNotificationsRead,
  getUpcomingExpirations,
  getMonthlyRevenue,
}
