/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CariRouteImport } from './routes/cari'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as protectedAdminRouteRouteImport } from './routes/(protected)/admin/route'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiSseRouteImport } from './routes/api/sse'
import { Route as BookingBookingIdRouteImport } from './routes/booking/$bookingId'
import { Route as OwnerPropertiesRouteImport } from './routes/owner.properties'
import { Route as PropertiesIdRouteImport } from './routes/properties/$id'
import { Route as protectedAdminIndexRouteImport } from './routes/(protected)/admin/index'
import { Route as protectedAdminBookingsRouteImport } from './routes/(protected)/admin/bookings'
import { Route as protectedAdminKonfigurasiRouteImport } from './routes/(protected)/admin/konfigurasi'
import { Route as protectedAdminUsersRouteImport } from './routes/(protected)/admin/users'
import { Route as protectedAdminVerificationRouteImport } from './routes/(protected)/admin/verification'
import { Route as protectedPemilikDashboardRouteRouteImport } from './routes/(protected)/pemilik/dashboard/route'
import { Route as protectedPenyewaBookingRouteImport } from './routes/(protected)/penyewa/booking'
import { Route as protectedPenyewaWishlistRouteImport } from './routes/(protected)/penyewa/wishlist'
import { Route as publicPropertiPropertyIdRouteImport } from './routes/(public)/properti/$propertyId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronCancelExpiredBookingsRouteImport } from './routes/api/cron/cancel-expired-bookings'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiWebhooksMidtransRouteImport } from './routes/api/webhooks/midtrans'
import { Route as ApiWebhooksPaymentRouteImport } from './routes/api/webhooks/payment'
import { Route as OwnerPropertiesIdRouteImport } from './routes/owner.properties.$id'
import { Route as OwnerPropertiesNewRouteImport } from './routes/owner.properties.new'
import { Route as protectedPemilikDashboardIndexRouteImport } from './routes/(protected)/pemilik/dashboard/index'
import { Route as protectedPemilikDashboardActiveRouteImport } from './routes/(protected)/pemilik/dashboard/active'
import { Route as protectedPemilikDashboardExpirationsRouteImport } from './routes/(protected)/pemilik/dashboard/expirations'
import { Route as protectedPemilikDashboardHistoryRouteImport } from './routes/(protected)/pemilik/dashboard/history'
import { Route as protectedPemilikDashboardMessagesRouteImport } from './routes/(protected)/pemilik/dashboard/messages'
import { Route as protectedPemilikDashboardRequestsRouteImport } from './routes/(protected)/pemilik/dashboard/requests'
import { Route as protectedPenyewaBookingBaruRouteImport } from './routes/(protected)/penyewa/booking/baru'
import { Route as ApiWebhooksQstashSplatRouteImport } from './routes/api/webhooks/qstash/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CariRoute = CariRouteImport.update({
  id: '/cari',
  path: '/cari',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAdminRouteRoute = protectedAdminRouteRouteImport.update({
  id: '/(protected)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSseRoute = ApiSseRouteImport.update({
  id: '/api/sse',
  path: '/api/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingIdRoute = BookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertiesRoute = OwnerPropertiesRouteImport.update({
  id: '/owner/properties',
  path: '/owner/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const protectedAdminIndexRoute = protectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedAdminRouteRoute,
} as any)
const protectedAdminBookingsRoute = protectedAdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => protectedAdminRouteRoute,
} as any)
const protectedAdminKonfigurasiRoute =
  protectedAdminKonfigurasiRouteImport.update({
    id: '/konfigurasi',
    path: '/konfigurasi',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedAdminUsersRoute = protectedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => protectedAdminRouteRoute,
} as any)
const protectedAdminVerificationRoute =
  protectedAdminVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedPemilikDashboardRouteRoute =
  protectedPemilikDashboardRouteRouteImport.update({
    id: '/(protected)/pemilik/dashboard',
    path: '/pemilik/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const protectedPenyewaBookingRoute = protectedPenyewaBookingRouteImport.update({
  id: '/(protected)/penyewa/booking',
  path: '/penyewa/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedPenyewaWishlistRoute =
  protectedPenyewaWishlistRouteImport.update({
    id: '/(protected)/penyewa/wishlist',
    path: '/penyewa/wishlist',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicPropertiPropertyIdRoute =
  publicPropertiPropertyIdRouteImport.update({
    id: '/(public)/properti/$propertyId',
    path: '/properti/$propertyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCancelExpiredBookingsRoute =
  ApiCronCancelExpiredBookingsRouteImport.update({
    id: '/api/cron/cancel-expired-bookings',
    path: '/api/cron/cancel-expired-bookings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMidtransRoute = ApiWebhooksMidtransRouteImport.update({
  id: '/api/webhooks/midtrans',
  path: '/api/webhooks/midtrans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaymentRoute = ApiWebhooksPaymentRouteImport.update({
  id: '/api/webhooks/payment',
  path: '/api/webhooks/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertiesIdRoute = OwnerPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OwnerPropertiesRoute,
} as any)
const OwnerPropertiesNewRoute = OwnerPropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerPropertiesRoute,
} as any)
const protectedPemilikDashboardIndexRoute =
  protectedPemilikDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedPemilikDashboardRouteRoute,
  } as any)
const protectedPemilikDashboardActiveRoute =
  protectedPemilikDashboardActiveRouteImport.update({
    id: '/active',
    path: '/active',
    getParentRoute: () => protectedPemilikDashboardRouteRoute,
  } as any)
const protectedPemilikDashboardExpirationsRoute =
  protectedPemilikDashboardExpirationsRouteImport.update({
    id: '/expirations',
    path: '/expirations',
    getParentRoute: () => protectedPemilikDashboardRouteRoute,
  } as any)
const protectedPemilikDashboardHistoryRoute =
  protectedPemilikDashboardHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => protectedPemilikDashboardRouteRoute,
  } as any)
const protectedPemilikDashboardMessagesRoute =
  protectedPemilikDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => protectedPemilikDashboardRouteRoute,
  } as any)
const protectedPemilikDashboardRequestsRoute =
  protectedPemilikDashboardRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => protectedPemilikDashboardRouteRoute,
  } as any)
const protectedPenyewaBookingBaruRoute =
  protectedPenyewaBookingBaruRouteImport.update({
    id: '/baru',
    path: '/baru',
    getParentRoute: () => protectedPenyewaBookingRoute,
  } as any)
const ApiWebhooksQstashSplatRoute = ApiWebhooksQstashSplatRouteImport.update({
  id: '/api/webhooks/qstash/$',
  path: '/api/webhooks/qstash/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cari': typeof CariRoute
  '/mcp': typeof McpRoute
  '/pengaturan': typeof PengaturanRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/admin': typeof protectedAdminRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/sse': typeof ApiSseRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/owner/properties': typeof OwnerPropertiesRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/pemilik/dashboard': typeof protectedPemilikDashboardRouteRouteWithChildren
  '/admin/bookings': typeof protectedAdminBookingsRoute
  '/admin/konfigurasi': typeof protectedAdminKonfigurasiRoute
  '/admin/users': typeof protectedAdminUsersRoute
  '/admin/verification': typeof protectedAdminVerificationRoute
  '/penyewa/booking': typeof protectedPenyewaBookingRouteWithChildren
  '/penyewa/wishlist': typeof protectedPenyewaWishlistRoute
  '/properti/$propertyId': typeof publicPropertiPropertyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/cancel-expired-bookings': typeof ApiCronCancelExpiredBookingsRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/midtrans': typeof ApiWebhooksMidtransRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/owner/properties/$id': typeof OwnerPropertiesIdRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/admin/': typeof protectedAdminIndexRoute
  '/pemilik/dashboard/active': typeof protectedPemilikDashboardActiveRoute
  '/pemilik/dashboard/expirations': typeof protectedPemilikDashboardExpirationsRoute
  '/pemilik/dashboard/history': typeof protectedPemilikDashboardHistoryRoute
  '/pemilik/dashboard/messages': typeof protectedPemilikDashboardMessagesRoute
  '/pemilik/dashboard/requests': typeof protectedPemilikDashboardRequestsRoute
  '/penyewa/booking/baru': typeof protectedPenyewaBookingBaruRoute
  '/api/webhooks/qstash/$': typeof ApiWebhooksQstashSplatRoute
  '/pemilik/dashboard/': typeof protectedPemilikDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cari': typeof CariRoute
  '/mcp': typeof McpRoute
  '/pengaturan': typeof PengaturanRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/sse': typeof ApiSseRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/owner/properties': typeof OwnerPropertiesRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/bookings': typeof protectedAdminBookingsRoute
  '/admin/konfigurasi': typeof protectedAdminKonfigurasiRoute
  '/admin/users': typeof protectedAdminUsersRoute
  '/admin/verification': typeof protectedAdminVerificationRoute
  '/penyewa/booking': typeof protectedPenyewaBookingRouteWithChildren
  '/penyewa/wishlist': typeof protectedPenyewaWishlistRoute
  '/properti/$propertyId': typeof publicPropertiPropertyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/cancel-expired-bookings': typeof ApiCronCancelExpiredBookingsRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/midtrans': typeof ApiWebhooksMidtransRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/owner/properties/$id': typeof OwnerPropertiesIdRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/admin': typeof protectedAdminIndexRoute
  '/pemilik/dashboard/active': typeof protectedPemilikDashboardActiveRoute
  '/pemilik/dashboard/expirations': typeof protectedPemilikDashboardExpirationsRoute
  '/pemilik/dashboard/history': typeof protectedPemilikDashboardHistoryRoute
  '/pemilik/dashboard/messages': typeof protectedPemilikDashboardMessagesRoute
  '/pemilik/dashboard/requests': typeof protectedPemilikDashboardRequestsRoute
  '/penyewa/booking/baru': typeof protectedPenyewaBookingBaruRoute
  '/api/webhooks/qstash/$': typeof ApiWebhooksQstashSplatRoute
  '/pemilik/dashboard': typeof protectedPemilikDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/cari': typeof CariRoute
  '/mcp': typeof McpRoute
  '/pengaturan': typeof PengaturanRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/(protected)/admin': typeof protectedAdminRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/sse': typeof ApiSseRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/owner/properties': typeof OwnerPropertiesRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/(protected)/pemilik/dashboard': typeof protectedPemilikDashboardRouteRouteWithChildren
  '/(protected)/admin/bookings': typeof protectedAdminBookingsRoute
  '/(protected)/admin/konfigurasi': typeof protectedAdminKonfigurasiRoute
  '/(protected)/admin/users': typeof protectedAdminUsersRoute
  '/(protected)/admin/verification': typeof protectedAdminVerificationRoute
  '/(protected)/penyewa/booking': typeof protectedPenyewaBookingRouteWithChildren
  '/(protected)/penyewa/wishlist': typeof protectedPenyewaWishlistRoute
  '/(public)/properti/$propertyId': typeof publicPropertiPropertyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/cancel-expired-bookings': typeof ApiCronCancelExpiredBookingsRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/midtrans': typeof ApiWebhooksMidtransRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/owner/properties/$id': typeof OwnerPropertiesIdRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/(protected)/admin/': typeof protectedAdminIndexRoute
  '/(protected)/pemilik/dashboard/active': typeof protectedPemilikDashboardActiveRoute
  '/(protected)/pemilik/dashboard/expirations': typeof protectedPemilikDashboardExpirationsRoute
  '/(protected)/pemilik/dashboard/history': typeof protectedPemilikDashboardHistoryRoute
  '/(protected)/pemilik/dashboard/messages': typeof protectedPemilikDashboardMessagesRoute
  '/(protected)/pemilik/dashboard/requests': typeof protectedPemilikDashboardRequestsRoute
  '/(protected)/penyewa/booking/baru': typeof protectedPenyewaBookingBaruRoute
  '/api/webhooks/qstash/$': typeof ApiWebhooksQstashSplatRoute
  '/(protected)/pemilik/dashboard/': typeof protectedPemilikDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cari'
    | '/mcp'
    | '/pengaturan'
    | '/properties'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/api/$'
    | '/api/sse'
    | '/booking/$bookingId'
    | '/owner/properties'
    | '/properties/$id'
    | '/pemilik/dashboard'
    | '/admin/bookings'
    | '/admin/konfigurasi'
    | '/admin/users'
    | '/admin/verification'
    | '/penyewa/booking'
    | '/penyewa/wishlist'
    | '/properti/$propertyId'
    | '/api/auth/$'
    | '/api/cron/cancel-expired-bookings'
    | '/api/rpc/$'
    | '/api/webhooks/midtrans'
    | '/api/webhooks/payment'
    | '/owner/properties/$id'
    | '/owner/properties/new'
    | '/admin/'
    | '/pemilik/dashboard/active'
    | '/pemilik/dashboard/expirations'
    | '/pemilik/dashboard/history'
    | '/pemilik/dashboard/messages'
    | '/pemilik/dashboard/requests'
    | '/penyewa/booking/baru'
    | '/api/webhooks/qstash/$'
    | '/pemilik/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cari'
    | '/mcp'
    | '/pengaturan'
    | '/properties'
    | '/sign-in'
    | '/sign-up'
    | '/api/$'
    | '/api/sse'
    | '/booking/$bookingId'
    | '/owner/properties'
    | '/properties/$id'
    | '/admin/bookings'
    | '/admin/konfigurasi'
    | '/admin/users'
    | '/admin/verification'
    | '/penyewa/booking'
    | '/penyewa/wishlist'
    | '/properti/$propertyId'
    | '/api/auth/$'
    | '/api/cron/cancel-expired-bookings'
    | '/api/rpc/$'
    | '/api/webhooks/midtrans'
    | '/api/webhooks/payment'
    | '/owner/properties/$id'
    | '/owner/properties/new'
    | '/admin'
    | '/pemilik/dashboard/active'
    | '/pemilik/dashboard/expirations'
    | '/pemilik/dashboard/history'
    | '/pemilik/dashboard/messages'
    | '/pemilik/dashboard/requests'
    | '/penyewa/booking/baru'
    | '/api/webhooks/qstash/$'
    | '/pemilik/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/cari'
    | '/mcp'
    | '/pengaturan'
    | '/properties'
    | '/(protected)/admin'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/api/$'
    | '/api/sse'
    | '/booking/$bookingId'
    | '/owner/properties'
    | '/properties/$id'
    | '/(protected)/pemilik/dashboard'
    | '/(protected)/admin/bookings'
    | '/(protected)/admin/konfigurasi'
    | '/(protected)/admin/users'
    | '/(protected)/admin/verification'
    | '/(protected)/penyewa/booking'
    | '/(protected)/penyewa/wishlist'
    | '/(public)/properti/$propertyId'
    | '/api/auth/$'
    | '/api/cron/cancel-expired-bookings'
    | '/api/rpc/$'
    | '/api/webhooks/midtrans'
    | '/api/webhooks/payment'
    | '/owner/properties/$id'
    | '/owner/properties/new'
    | '/(protected)/admin/'
    | '/(protected)/pemilik/dashboard/active'
    | '/(protected)/pemilik/dashboard/expirations'
    | '/(protected)/pemilik/dashboard/history'
    | '/(protected)/pemilik/dashboard/messages'
    | '/(protected)/pemilik/dashboard/requests'
    | '/(protected)/penyewa/booking/baru'
    | '/api/webhooks/qstash/$'
    | '/(protected)/pemilik/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  CariRoute: typeof CariRoute
  McpRoute: typeof McpRoute
  PengaturanRoute: typeof PengaturanRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  protectedAdminRouteRoute: typeof protectedAdminRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiSseRoute: typeof ApiSseRoute
  BookingBookingIdRoute: typeof BookingBookingIdRoute
  OwnerPropertiesRoute: typeof OwnerPropertiesRouteWithChildren
  protectedPemilikDashboardRouteRoute: typeof protectedPemilikDashboardRouteRouteWithChildren
  protectedPenyewaBookingRoute: typeof protectedPenyewaBookingRouteWithChildren
  protectedPenyewaWishlistRoute: typeof protectedPenyewaWishlistRoute
  publicPropertiPropertyIdRoute: typeof publicPropertiPropertyIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronCancelExpiredBookingsRoute: typeof ApiCronCancelExpiredBookingsRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiWebhooksMidtransRoute: typeof ApiWebhooksMidtransRoute
  ApiWebhooksPaymentRoute: typeof ApiWebhooksPaymentRoute
  ApiWebhooksQstashSplatRoute: typeof ApiWebhooksQstashSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari': {
      id: '/cari'
      path: '/cari'
      fullPath: '/cari'
      preLoaderRoute: typeof CariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/admin': {
      id: '/(protected)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof protectedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sse': {
      id: '/api/sse'
      path: '/api/sse'
      fullPath: '/api/sse'
      preLoaderRoute: typeof ApiSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingId': {
      id: '/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties': {
      id: '/owner/properties'
      path: '/owner/properties'
      fullPath: '/owner/properties'
      preLoaderRoute: typeof OwnerPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/(protected)/admin/': {
      id: '/(protected)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof protectedAdminIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/bookings': {
      id: '/(protected)/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof protectedAdminBookingsRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/konfigurasi': {
      id: '/(protected)/admin/konfigurasi'
      path: '/konfigurasi'
      fullPath: '/admin/konfigurasi'
      preLoaderRoute: typeof protectedAdminKonfigurasiRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/users': {
      id: '/(protected)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof protectedAdminUsersRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/verification': {
      id: '/(protected)/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof protectedAdminVerificationRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/pemilik/dashboard': {
      id: '/(protected)/pemilik/dashboard'
      path: '/pemilik/dashboard'
      fullPath: '/pemilik/dashboard'
      preLoaderRoute: typeof protectedPemilikDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/penyewa/booking': {
      id: '/(protected)/penyewa/booking'
      path: '/penyewa/booking'
      fullPath: '/penyewa/booking'
      preLoaderRoute: typeof protectedPenyewaBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/penyewa/wishlist': {
      id: '/(protected)/penyewa/wishlist'
      path: '/penyewa/wishlist'
      fullPath: '/penyewa/wishlist'
      preLoaderRoute: typeof protectedPenyewaWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/properti/$propertyId': {
      id: '/(public)/properti/$propertyId'
      path: '/properti/$propertyId'
      fullPath: '/properti/$propertyId'
      preLoaderRoute: typeof publicPropertiPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/cancel-expired-bookings': {
      id: '/api/cron/cancel-expired-bookings'
      path: '/api/cron/cancel-expired-bookings'
      fullPath: '/api/cron/cancel-expired-bookings'
      preLoaderRoute: typeof ApiCronCancelExpiredBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/midtrans': {
      id: '/api/webhooks/midtrans'
      path: '/api/webhooks/midtrans'
      fullPath: '/api/webhooks/midtrans'
      preLoaderRoute: typeof ApiWebhooksMidtransRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/payment': {
      id: '/api/webhooks/payment'
      path: '/api/webhooks/payment'
      fullPath: '/api/webhooks/payment'
      preLoaderRoute: typeof ApiWebhooksPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties/$id': {
      id: '/owner/properties/$id'
      path: '/$id'
      fullPath: '/owner/properties/$id'
      preLoaderRoute: typeof OwnerPropertiesIdRouteImport
      parentRoute: typeof OwnerPropertiesRoute
    }
    '/owner/properties/new': {
      id: '/owner/properties/new'
      path: '/new'
      fullPath: '/owner/properties/new'
      preLoaderRoute: typeof OwnerPropertiesNewRouteImport
      parentRoute: typeof OwnerPropertiesRoute
    }
    '/(protected)/pemilik/dashboard/': {
      id: '/(protected)/pemilik/dashboard/'
      path: '/'
      fullPath: '/pemilik/dashboard/'
      preLoaderRoute: typeof protectedPemilikDashboardIndexRouteImport
      parentRoute: typeof protectedPemilikDashboardRouteRoute
    }
    '/(protected)/pemilik/dashboard/active': {
      id: '/(protected)/pemilik/dashboard/active'
      path: '/active'
      fullPath: '/pemilik/dashboard/active'
      preLoaderRoute: typeof protectedPemilikDashboardActiveRouteImport
      parentRoute: typeof protectedPemilikDashboardRouteRoute
    }
    '/(protected)/pemilik/dashboard/expirations': {
      id: '/(protected)/pemilik/dashboard/expirations'
      path: '/expirations'
      fullPath: '/pemilik/dashboard/expirations'
      preLoaderRoute: typeof protectedPemilikDashboardExpirationsRouteImport
      parentRoute: typeof protectedPemilikDashboardRouteRoute
    }
    '/(protected)/pemilik/dashboard/history': {
      id: '/(protected)/pemilik/dashboard/history'
      path: '/history'
      fullPath: '/pemilik/dashboard/history'
      preLoaderRoute: typeof protectedPemilikDashboardHistoryRouteImport
      parentRoute: typeof protectedPemilikDashboardRouteRoute
    }
    '/(protected)/pemilik/dashboard/messages': {
      id: '/(protected)/pemilik/dashboard/messages'
      path: '/messages'
      fullPath: '/pemilik/dashboard/messages'
      preLoaderRoute: typeof protectedPemilikDashboardMessagesRouteImport
      parentRoute: typeof protectedPemilikDashboardRouteRoute
    }
    '/(protected)/pemilik/dashboard/requests': {
      id: '/(protected)/pemilik/dashboard/requests'
      path: '/requests'
      fullPath: '/pemilik/dashboard/requests'
      preLoaderRoute: typeof protectedPemilikDashboardRequestsRouteImport
      parentRoute: typeof protectedPemilikDashboardRouteRoute
    }
    '/(protected)/penyewa/booking/baru': {
      id: '/(protected)/penyewa/booking/baru'
      path: '/baru'
      fullPath: '/penyewa/booking/baru'
      preLoaderRoute: typeof protectedPenyewaBookingBaruRouteImport
      parentRoute: typeof protectedPenyewaBookingRoute
    }
    '/api/webhooks/qstash/$': {
      id: '/api/webhooks/qstash/$'
      path: '/api/webhooks/qstash/$'
      fullPath: '/api/webhooks/qstash/$'
      preLoaderRoute: typeof ApiWebhooksQstashSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

interface protectedAdminRouteRouteChildren {
  protectedAdminBookingsRoute: typeof protectedAdminBookingsRoute
  protectedAdminKonfigurasiRoute: typeof protectedAdminKonfigurasiRoute
  protectedAdminUsersRoute: typeof protectedAdminUsersRoute
  protectedAdminVerificationRoute: typeof protectedAdminVerificationRoute
  protectedAdminIndexRoute: typeof protectedAdminIndexRoute
}

const protectedAdminRouteRouteChildren: protectedAdminRouteRouteChildren = {
  protectedAdminBookingsRoute: protectedAdminBookingsRoute,
  protectedAdminKonfigurasiRoute: protectedAdminKonfigurasiRoute,
  protectedAdminUsersRoute: protectedAdminUsersRoute,
  protectedAdminVerificationRoute: protectedAdminVerificationRoute,
  protectedAdminIndexRoute: protectedAdminIndexRoute,
}

const protectedAdminRouteRouteWithChildren =
  protectedAdminRouteRoute._addFileChildren(protectedAdminRouteRouteChildren)

interface OwnerPropertiesRouteChildren {
  OwnerPropertiesIdRoute: typeof OwnerPropertiesIdRoute
  OwnerPropertiesNewRoute: typeof OwnerPropertiesNewRoute
}

const OwnerPropertiesRouteChildren: OwnerPropertiesRouteChildren = {
  OwnerPropertiesIdRoute: OwnerPropertiesIdRoute,
  OwnerPropertiesNewRoute: OwnerPropertiesNewRoute,
}

const OwnerPropertiesRouteWithChildren = OwnerPropertiesRoute._addFileChildren(
  OwnerPropertiesRouteChildren,
)

interface protectedPemilikDashboardRouteRouteChildren {
  protectedPemilikDashboardActiveRoute: typeof protectedPemilikDashboardActiveRoute
  protectedPemilikDashboardExpirationsRoute: typeof protectedPemilikDashboardExpirationsRoute
  protectedPemilikDashboardHistoryRoute: typeof protectedPemilikDashboardHistoryRoute
  protectedPemilikDashboardMessagesRoute: typeof protectedPemilikDashboardMessagesRoute
  protectedPemilikDashboardRequestsRoute: typeof protectedPemilikDashboardRequestsRoute
  protectedPemilikDashboardIndexRoute: typeof protectedPemilikDashboardIndexRoute
}

const protectedPemilikDashboardRouteRouteChildren: protectedPemilikDashboardRouteRouteChildren =
  {
    protectedPemilikDashboardActiveRoute: protectedPemilikDashboardActiveRoute,
    protectedPemilikDashboardExpirationsRoute:
      protectedPemilikDashboardExpirationsRoute,
    protectedPemilikDashboardHistoryRoute:
      protectedPemilikDashboardHistoryRoute,
    protectedPemilikDashboardMessagesRoute:
      protectedPemilikDashboardMessagesRoute,
    protectedPemilikDashboardRequestsRoute:
      protectedPemilikDashboardRequestsRoute,
    protectedPemilikDashboardIndexRoute: protectedPemilikDashboardIndexRoute,
  }

const protectedPemilikDashboardRouteRouteWithChildren =
  protectedPemilikDashboardRouteRoute._addFileChildren(
    protectedPemilikDashboardRouteRouteChildren,
  )

interface protectedPenyewaBookingRouteChildren {
  protectedPenyewaBookingBaruRoute: typeof protectedPenyewaBookingBaruRoute
}

const protectedPenyewaBookingRouteChildren: protectedPenyewaBookingRouteChildren =
  {
    protectedPenyewaBookingBaruRoute: protectedPenyewaBookingBaruRoute,
  }

const protectedPenyewaBookingRouteWithChildren =
  protectedPenyewaBookingRoute._addFileChildren(
    protectedPenyewaBookingRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  CariRoute: CariRoute,
  McpRoute: McpRoute,
  PengaturanRoute: PengaturanRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  protectedAdminRouteRoute: protectedAdminRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiSseRoute: ApiSseRoute,
  BookingBookingIdRoute: BookingBookingIdRoute,
  OwnerPropertiesRoute: OwnerPropertiesRouteWithChildren,
  protectedPemilikDashboardRouteRoute:
    protectedPemilikDashboardRouteRouteWithChildren,
  protectedPenyewaBookingRoute: protectedPenyewaBookingRouteWithChildren,
  protectedPenyewaWishlistRoute: protectedPenyewaWishlistRoute,
  publicPropertiPropertyIdRoute: publicPropertiPropertyIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronCancelExpiredBookingsRoute: ApiCronCancelExpiredBookingsRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiWebhooksMidtransRoute: ApiWebhooksMidtransRoute,
  ApiWebhooksPaymentRoute: ApiWebhooksPaymentRoute,
  ApiWebhooksQstashSplatRoute: ApiWebhooksQstashSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
