/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as OwnerPropertiesRouteImport } from './routes/owner.properties'
import { Route as PropertiesIdRouteImport } from './routes/properties/$id'
import { Route as protectedPenyewaBookingRouteImport } from './routes/(protected)/penyewa/booking'
import { Route as publicPropertiPropertyIdRouteImport } from './routes/(public)/properti/$propertyId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as OwnerPropertiesNewRouteImport } from './routes/owner.properties.new'
import { Route as protectedPenyewaBookingBaruRouteImport } from './routes/(protected)/penyewa/booking/baru'
import { Route as ApiWebhooksQstashSplatRouteImport } from './routes/api/webhooks/qstash/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertiesRoute = OwnerPropertiesRouteImport.update({
  id: '/owner/properties',
  path: '/owner/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const protectedPenyewaBookingRoute = protectedPenyewaBookingRouteImport.update({
  id: '/(protected)/penyewa/booking',
  path: '/penyewa/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPropertiPropertyIdRoute =
  publicPropertiPropertyIdRouteImport.update({
    id: '/(public)/properti/$propertyId',
    path: '/properti/$propertyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertiesNewRoute = OwnerPropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerPropertiesRoute,
} as any)
const protectedPenyewaBookingBaruRoute =
  protectedPenyewaBookingBaruRouteImport.update({
    id: '/baru',
    path: '/baru',
    getParentRoute: () => protectedPenyewaBookingRoute,
  } as any)
const ApiWebhooksQstashSplatRoute = ApiWebhooksQstashSplatRouteImport.update({
  id: '/api/webhooks/qstash/$',
  path: '/api/webhooks/qstash/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/$': typeof ApiSplatRoute
  '/owner/properties': typeof OwnerPropertiesRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/penyewa/booking': typeof protectedPenyewaBookingRouteWithChildren
  '/properti/$propertyId': typeof publicPropertiPropertyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/penyewa/booking/baru': typeof protectedPenyewaBookingBaruRoute
  '/api/webhooks/qstash/$': typeof ApiWebhooksQstashSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/$': typeof ApiSplatRoute
  '/owner/properties': typeof OwnerPropertiesRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/penyewa/booking': typeof protectedPenyewaBookingRouteWithChildren
  '/properti/$propertyId': typeof publicPropertiPropertyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/penyewa/booking/baru': typeof protectedPenyewaBookingBaruRoute
  '/api/webhooks/qstash/$': typeof ApiWebhooksQstashSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/api/$': typeof ApiSplatRoute
  '/owner/properties': typeof OwnerPropertiesRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/(protected)/penyewa/booking': typeof protectedPenyewaBookingRouteWithChildren
  '/(public)/properti/$propertyId': typeof publicPropertiPropertyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/(protected)/penyewa/booking/baru': typeof protectedPenyewaBookingBaruRoute
  '/api/webhooks/qstash/$': typeof ApiWebhooksQstashSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/mcp'
    | '/properties'
    | '/sign-in'
    | '/sign-up'
    | '/api/$'
    | '/owner/properties'
    | '/properties/$id'
    | '/penyewa/booking'
    | '/properti/$propertyId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/owner/properties/new'
    | '/penyewa/booking/baru'
    | '/api/webhooks/qstash/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/mcp'
    | '/properties'
    | '/sign-in'
    | '/sign-up'
    | '/api/$'
    | '/owner/properties'
    | '/properties/$id'
    | '/penyewa/booking'
    | '/properti/$propertyId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/owner/properties/new'
    | '/penyewa/booking/baru'
    | '/api/webhooks/qstash/$'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/mcp'
    | '/properties'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/api/$'
    | '/owner/properties'
    | '/properties/$id'
    | '/(protected)/penyewa/booking'
    | '/(public)/properti/$propertyId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/owner/properties/new'
    | '/(protected)/penyewa/booking/baru'
    | '/api/webhooks/qstash/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  McpRoute: typeof McpRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  OwnerPropertiesRoute: typeof OwnerPropertiesRouteWithChildren
  protectedPenyewaBookingRoute: typeof protectedPenyewaBookingRouteWithChildren
  publicPropertiPropertyIdRoute: typeof publicPropertiPropertyIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiWebhooksQstashSplatRoute: typeof ApiWebhooksQstashSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties': {
      id: '/owner/properties'
      path: '/owner/properties'
      fullPath: '/owner/properties'
      preLoaderRoute: typeof OwnerPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/(protected)/penyewa/booking': {
      id: '/(protected)/penyewa/booking'
      path: '/penyewa/booking'
      fullPath: '/penyewa/booking'
      preLoaderRoute: typeof protectedPenyewaBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/properti/$propertyId': {
      id: '/(public)/properti/$propertyId'
      path: '/properti/$propertyId'
      fullPath: '/properti/$propertyId'
      preLoaderRoute: typeof publicPropertiPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties/new': {
      id: '/owner/properties/new'
      path: '/new'
      fullPath: '/owner/properties/new'
      preLoaderRoute: typeof OwnerPropertiesNewRouteImport
      parentRoute: typeof OwnerPropertiesRoute
    }
    '/(protected)/penyewa/booking/baru': {
      id: '/(protected)/penyewa/booking/baru'
      path: '/baru'
      fullPath: '/penyewa/booking/baru'
      preLoaderRoute: typeof protectedPenyewaBookingBaruRouteImport
      parentRoute: typeof protectedPenyewaBookingRoute
    }
    '/api/webhooks/qstash/$': {
      id: '/api/webhooks/qstash/$'
      path: '/api/webhooks/qstash/$'
      fullPath: '/api/webhooks/qstash/$'
      preLoaderRoute: typeof ApiWebhooksQstashSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

interface OwnerPropertiesRouteChildren {
  OwnerPropertiesNewRoute: typeof OwnerPropertiesNewRoute
}

const OwnerPropertiesRouteChildren: OwnerPropertiesRouteChildren = {
  OwnerPropertiesNewRoute: OwnerPropertiesNewRoute,
}

const OwnerPropertiesRouteWithChildren = OwnerPropertiesRoute._addFileChildren(
  OwnerPropertiesRouteChildren,
)

interface protectedPenyewaBookingRouteChildren {
  protectedPenyewaBookingBaruRoute: typeof protectedPenyewaBookingBaruRoute
}

const protectedPenyewaBookingRouteChildren: protectedPenyewaBookingRouteChildren =
  {
    protectedPenyewaBookingBaruRoute: protectedPenyewaBookingBaruRoute,
  }

const protectedPenyewaBookingRouteWithChildren =
  protectedPenyewaBookingRoute._addFileChildren(
    protectedPenyewaBookingRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  McpRoute: McpRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  OwnerPropertiesRoute: OwnerPropertiesRouteWithChildren,
  protectedPenyewaBookingRoute: protectedPenyewaBookingRouteWithChildren,
  publicPropertiPropertyIdRoute: publicPropertiPropertyIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiWebhooksQstashSplatRoute: ApiWebhooksQstashSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
